name: root
channels:
- r
- defaults
dependencies:
- _nb_ext_conf=0.2.0=py27_0
- alabaster=0.7.8=py27_0
- anaconda-client=1.4.0=py27_0
- anaconda=custom=py27_0
- anaconda-navigator=1.2.1=py27_0
- appnope=0.1.0=py27_0
- appscript=1.0.1=py27_0
- argcomplete=1.0.0=py27_1
- astroid=1.4.4=py27_0
- astropy=1.2.1=np111py27_0
- babel=2.3.3=py27_0
- backports=1.0=py27_0
- backports_abc=0.4=py27_0
- beautifulsoup4=4.4.1=py27_0
- bitarray=0.8.1=py27_0
- blaze=0.10.1=py27_0
- bokeh=0.12.0=py27_0
- boto=2.40.0=py27_0
- bottleneck=1.1.0=np111py27_0
- cdecimal=2.3=py27_2
- cffi=1.6.0=py27_0
- chest=0.2.3=py27_0
- click=6.6=py27_0
- cloudpickle=0.2.1=py27_0
- clyent=1.2.2=py27_0
- colorama=0.3.7=py27_0
- conda=4.1.11=py27_0
- conda-build=1.21.3=py27_0
- conda-env=2.5.2=py27_0
- configobj=5.0.6=py27_0
- configparser=3.5.0b2=py27_1
- contextlib2=0.5.3=py27_0
- cryptography=1.4=py27_0
- curl=7.49.0=0
- cycler=0.10.0=py27_0
- cython=0.24=py27_0
- cytoolz=0.8.0=py27_0
- dask=0.10.0=py27_0
- datashape=0.5.2=py27_0
- decorator=4.0.10=py27_0
- dill=0.2.5=py27_0
- docutils=0.12=py27_2
- dynd-python=0.7.2=py27_0
- entrypoints=0.2.2=py27_0
- enum34=1.1.6=py27_0
- et_xmlfile=1.0.1=py27_0
- fastcache=1.0.2=py27_1
- flask=0.11.1=py27_0
- flask-cors=2.1.2=py27_0
- freetype=2.5.5=1
- funcsigs=1.0.2=py27_0
- functools32=3.2.3.2=py27_0
- futures=3.0.5=py27_0
- get_terminal_size=1.0.0=py27_0
- gevent=1.1.1=py27_0
- greenlet=0.4.10=py27_0
- grin=1.2.1=py27_3
- h5py=2.6.0=np111py27_2
- hdf5=1.8.17=1
- heapdict=1.0.0=py27_1
- idna=2.1=py27_0
- imagesize=0.7.1=py27_0
- ipaddress=1.0.16=py27_0
- ipykernel=4.3.1=py27_0
- ipython=5.1.0=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=4.1.1=py27_0
- itsdangerous=0.24=py27_0
- jbig=2.1=0
- jdcal=1.2=py27_1
- jedi=0.9.0=py27_1
- jinja2=2.8=py27_1
- jpeg=8d=1
- jsonschema=2.5.1=py27_0
- jupyter=1.0.0=py27_3
- jupyter_client=4.3.0=py27_0
- jupyter_console=5.0.0=py27_0
- jupyter_core=4.1.1=py27_0
- lazy-object-proxy=1.2.1=py27_0
- libdynd=0.7.2=0
- libpng=1.6.22=0
- libtiff=4.0.6=2
- libxml2=2.9.2=0
- libxslt=1.1.28=2
- llvmlite=0.12.1=py27_0
- locket=0.2.0=py27_1
- logilab-common=1.0.2=py27_0
- lxml=3.6.0=py27_0
- markupsafe=0.23=py27_2
- matplotlib=1.5.1=np111py27_0
- mistune=0.7.2=py27_1
- mkl=11.3.3=0
- mkl-service=1.1.2=py27_2
- mpmath=0.19=py27_1
- multipledispatch=0.4.8=py27_0
- nb_anacondacloud=1.1.0=py27_0
- nb_conda=1.1.0=py27_0
- nb_conda_kernels=1.0.3=py27_0
- nbconvert=4.2.0=py27_0
- nbformat=4.0.1=py27_0
- nbpresent=3.0.2=py27_0
- networkx=1.11=py27_0
- nltk=3.2.1=py27_0
- nose=1.3.7=py27_1
- notebook=4.2.1=py27_0
- numba=0.27.0=np111py27_0
- numba::llvmdev=3.7.1=2
- numexpr=2.6.0=np111py27_0
- numpy=1.11.1=py27_0
- odo=0.5.0=py27_1
- openpyxl=2.3.2=py27_0
- openssl=1.0.2h=1
- pandas=0.18.1=np111py27_0
- partd=0.3.4=py27_0
- path.py=8.2.1=py27_0
- pathlib2=2.1.0=py27_0
- patsy=0.4.1=py27_0
- pep8=1.7.0=py27_0
- pexpect=4.0.1=py27_0
- pickleshare=0.7.2=py27_0
- pillow=3.2.0=py27_1
- pip=8.1.2=py27_0
- ply=3.8=py27_0
- prompt_toolkit=1.0.3=py27_0
- psutil=4.3.0=py27_0
- ptyprocess=0.5.1=py27_0
- py=1.4.31=py27_0
- pyasn1=0.1.9=py27_0
- pyaudio=0.2.7=py27_0
- pycosat=0.6.1=py27_1
- pycparser=2.14=py27_1
- pycrypto=2.6.1=py27_4
- pycurl=7.43.0=py27_0
- pyflakes=1.2.3=py27_0
- pygments=2.1.3=py27_0
- pylint=1.5.4=py27_0
- pyopenssl=0.16.0=py27_0
- pyparsing=2.1.4=py27_0
- pyqt=4.11.4=py27_3
- pytables=3.2.3.1=np111py27_0
- pytest=2.9.2=py27_0
- python=2.7.12=1
- python-dateutil=2.5.3=py27_0
- python.app=1.2=py27_4
- pytz=2016.4=py27_0
- pyyaml=3.11=py27_4
- pyzmq=15.2.0=py27_1
- qt=4.8.7=3
- qtconsole=4.2.1=py27_0
- qtpy=1.0.2=py27_0
- readline=6.2=2
- redis=3.2.0=0
- redis-py=2.10.5=py27_0
- requests=2.10.0=py27_0
- rope=0.9.4=py27_1
- ruamel_yaml=0.11.7=py27_0
- scikit-image=0.12.3=np111py27_1
- scikit-learn=0.17.1=np111py27_2
- scipy=0.17.1=np111py27_1
- setuptools=23.0.0=py27_0
- setuptools_scm=1.9.0=py27_0
- simplegeneric=0.8.1=py27_1
- singledispatch=3.4.0.3=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- snowballstemmer=1.2.1=py27_0
- sockjs-tornado=1.0.3=py27_0
- sphinx=1.4.1=py27_0
- sphinx_rtd_theme=0.1.9=py27_0
- spyder=2.3.9=py27_0
- sqlalchemy=1.0.13=py27_0
- sqlite=3.13.0=0
- ssl_match_hostname=3.4.0.2=py27_1
- statsmodels=0.6.1=np111py27_1
- sympy=1.0=py27_0
- terminado=0.6=py27_0
- tk=8.5.18=0
- toolz=0.8.0=py27_0
- tornado=4.3=py27_1
- traitlets=4.2.1=py27_0
- unicodecsv=0.14.1=py27_0
- wcwidth=0.1.7=py27_0
- werkzeug=0.11.10=py27_0
- wheel=0.29.0=py27_0
- wrapt=1.10.6=py27_0
- xlrd=1.0.0=py27_0
- xlsxwriter=0.9.2=py27_0
- xlwings=0.7.2=py27_0
- xlwt=1.1.2=py27_0
- xz=5.2.2=0
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - asciitree==0.3.2
  - autopep8==1.2.4
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.4.0.2
  - bidict==0.12.0
  - build-capi==0.0.5
  - colour==0.1.2
  - dynd==0.7.3.dev1
  - et-xmlfile==1.0.1
  - glob2==0.4.1
  - hcache==0.0.8
  - humanfriendly==1.44.7
  - ipdb==0.10.1
  - ipython-genutils==0.1.0
  - jupyter-client==4.3.0
  - jupyter-console==5.0.0
  - jupyter-core==4.1.1
  - limix-math==0.2.5
  - limix-tool==0.1.17
  - limix-util==0.0.11
  - nb-anacondacloud==1.1.0
  - nb-conda==1.1.0
  - nb-conda-kernels==1.0.3
  - ncephes==0.0.33
  - progressbar2==3.10.0
  - prompt-toolkit==1.0.3
  - python-utils==2.0.0
  - setuptools-scm==1.9.0
  - sphinx-rtd-theme==0.1.9
  - sphinxcontrib-programoutput==0.8
  - tables==3.2.3.1
  - tabulate==0.7.5
